title: aprendendo html e css3
description: utilizando html5 e css3
template:
  repo: aprendendo-html-e-css3-template
  name: aprendendo-html-e-css3
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
